export const ACCOUNTS_GET_PARAMETER =
  "or451";
export const LOAD_ACCOUNTS_REQUEST = "LOAD_ACCOUNTS_REQUEST";
export const LOAD_ACCOUNTS_SUCCESS = "LOAD_ACCOUNTS_SUCCESS";
export const LOAD_ACCOUNTS_FAILURE = "LOAD_ACCOUNTS_FAILURE";


/*
Reimburse Details Api
*/
export const REIMBURSE_DETAILS_GET_PARAMETER='16i7p9';
export const REIMBURSE_DETAILS_DATA_REQUEST='REIMBURSE_DETAILS_DATA_REQUEST';
export const REIMBURSE_DETAILS_DATA_FAILED='REIMBURSE_DETAILS_DATA_FAILED';
export const REIMBURSE_DETAILS_DATA_SUCCESS='REIMBURSE_DETAILS_DATA_SUCCESS';




